export default new Model({
  title: '',
  charge: 0,
  short_description: '',
  description: '',
  seo_keywords: '',
  seo_description: '',
  published_at: '',
  is_show: null,
  aliyun_video_id: '',
  tencent_video_id: '',
  url: '',
  duration: null,
  is_ban_sell: null,
  comment_status: null,
  ban_drag: null,
  free_seconds: null,
  player_pc: null,
  player_h5: null
});
